### ISSUE TITLE
[chore] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by RyuKwanKon** [KusitmsHDmedi/HDmedi_Server#1]
## Issue 🍃

프로젝트 초기 세팅입니다.

## Todo 🌴
- [x] issue template 만들기
- [x] pr template 만들기
- [x] spring docker 파일 제작
- [x] github action 연동하기
- [x] package 구조 만들기
