### ISSUE TITLE
[chore] ci/cd 연동

### ISSUE THREAD

**Issue by RyuKwanKon** [KusitmsHDmedi/HDmedi_Server#3]
## Issue 🍃

무중단 배포 & 자동 배포를 위한 infra 연동

## Todo 🌴
- [x] deploy.sh script 작성
- [x] workflow script 작성
- [x] secret key 등록
